template:
  name: k8s Canary Deployment
  identifier: k8s_Canary_Deployment
  versionLabel: "1"
  type: Step
  projectIdentifier: DoNotDelete_CD_Static_Schema_Signoff
  orgIdentifier: Ng_Pipelines_K8s_Organisations
  tags: {}
  spec:
    timeout: 10m
    type: K8sCanaryDeploy
    spec:
      skipDryRun: false
      instanceSelection:
        type: Count
        spec:
          count: 1
